name: Publish be image to Docker Hub
on:
  [workflow_dispatch]
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: pre-step
      shell: bash
      run: echo "release-version=$(echo ${GITHUB_REF:10})" >> $GITHUB_OUTPUT
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: myDocker/repository
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        tags: "latest,${{ steps.pre-step.outputs.release-version }}"

    - name: Notify on success
      if: success()
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{"text":"The BE publishing is succeeded for ${{ github.repository }} :rocket:"}' ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Notify on failure
      if: failure()
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{"text":"The BE publishing is failed for ${{ github.repository }} :x:"}' ${{ secrets.SLACK_WEBHOOK_URL }}
  
