name: Publish image to Docker Hub

on:
  workflow_dispatch:

env:
  DOCKER_HUB_IMAGE: projectred521/react-fe
  IMAGE_TAG: latest

jobs:
  publish_image:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build . -t $DOCKER_HUB_IMAGE:$IMAGE_TAG
        continue-on-error: true

      - name: Publish Docker image
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: |
          docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_TOKEN
          docker push $DOCKER_HUB_IMAGE:$IMAGE_TAG

      - name: Clean up Docker images
        run: |
          docker image prune -f
