name: Publish FE

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'fe-react/**'
    tags:
      - 'v*'


jobs:
  docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: fe-react
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: projectred521/react-f
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: fe-react
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}