name: CI Tests be

on:
  push:
    paths:
      - 'bigid/be-flask/**'
  workflow_dispatch:  # This event allows manual triggering

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r be-flask/requirements.txt

      - name: Start Server
        run: |
          python be-flask/app.py &  # Start the server in the background
          sleep 5  # Give the server some time to start (adjust as needed)

      - name: Run integration tests
        run: |
          python be-flask/test_integration.py
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}  # Set Slack webhook URL as an environment variable
        if: ${{ success() }}  # Only run if previous step succeeded

      - name: Run unit tests
        run: |
          python be-flask/test_unit.py
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}  # Set Slack webhook URL as an environment variable
        if: ${{ success() }}  # Only run if previous step succeeded

      - name: Stop Server
        run: |
          pkill -f app.py  # Stop the server gracefully

      - name: Notify on status
        if: always()  # Notify on both success and failure
        run: |
          if [[ ${{ success() }} == 'true' ]]; then
            status_msg="succeeded"
            emoji=":white_check_mark:"
          else
            status_msg="failed"
            emoji=":x:"
          fi
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"Workflow $status_msg for ${{ github.repository }} $emoji\"}" $SLACK_WEBHOOK_URL
