name: CI Tests fe

on:
  push:
    branches:
      - main
    paths:
      - 'bigid/fe-react/**'
  workflow_dispatch:  

jobs:
  deployment:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: bigid/fe-react
      
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: check directory
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"The tests are succeeded for ${{ github.repository }} :rocket:"}' ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Install deps
        run: npm install
      - name: Test app
        run: npm run test
      - name: Lint code
        run: npm run lint
      # - name: Build App
      #   run: npm run build