name: CI Tests be

on:
  push:
    paths:
      - 'bigid/be-flask/**'
  workflow_dispatch:  # This event allows manual triggering

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r be-flask/requirements.txt

      - name: Start Server
        run: |
          python be-flask/app.py &  # Start the server in the background
          sleep 5  # Give the server some time to start (adjust as needed)

      - name: Run integration tests
        run: |
          python be-flask/test_integration.py

      # - name: Run unit tests
      #   run: |
      #     python be-flask/test_unit.py

      # - name: Stop Server
      #   run: |
      #     pkill -f app.py  # Stop the server gracefully
