name: CI Tests fe

on:
  push:
    branches:
      - main
    paths:
      - 'bigid/fe-react/**'
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 

      - name: Install dependencies
        # working-directory: bigid/fe-react  # Set the working directory
        run: npm install

      - name: Run tests
        # working-directory: bigid/fe-react  # Set the working directory
        run: npm test
